services:
  db-pgpy-test:
    image: postgres:13
    expose:
      - "5432"
    ports:
      - 5439:5432
    environment:
      POSTGRES_DB: pgpy
      POSTGRES_USER: agora
      POSTGRES_PASSWORD: agora
      POSTGRES_HOST: db
      POSTGRES_PORT: 5439
